# Generated by Django 3.1.13 on 2021-07-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20210722_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='show_pokemon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
