# Generated by Django 3.1.13 on 2021-07-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20210726_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemonentity'),
        ),
    ]
