# Generated by Django 3.1.13 on 2021-07-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20210726_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='english_name',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='japan_name',
            new_name='title_jp',
        ),
    ]
