# Generated by Django 3.1.13 on 2021-07-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0028_auto_20210727_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='Изображение'),
        ),
    ]
