# Generated by Django 3.1.13 on 2021-07-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0032_pokemon_element_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='element_type',
        ),
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='element_typy',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_typy',
            field=models.ManyToManyField(to='pokemon_entities.PokemonElementType'),
        ),
    ]
