# Generated by Django 3.1.13 on 2021-07-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0033_auto_20210728_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_typy',
            field=models.ManyToManyField(related_name='element_type', to='pokemon_entities.PokemonElementType'),
        ),
    ]
