# Generated by Django 3.1.13 on 2021-07-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0034_auto_20210728_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='element_typy',
            field=models.ManyToManyField(to='pokemon_entities.Pokemon'),
        ),
    ]
