# Generated by Django 3.1.13 on 2021-07-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0038_auto_20210728_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_typy',
            field=models.TextField(max_length=50),
        ),
    ]
