# Generated by Django 3.1.13 on 2021-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0045_remove_pokemon_element_typy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='element_typy',
            field=models.ManyToManyField(related_name='next_evolution', to='pokemon_entities.PokemonElementType'),
        ),
    ]
